services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - eventure-db
      - redis
    ports:
      - "3000:3000"
    environment:
      TZ: Asia/Kolkata
      REDIS_URL: ${REDIS_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  eventure-db:
    image: postgres:15
    container_name: ${DB_HOST}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]


volumes:
  pgdata:
